auth/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('auth',
    url(r'^weibo_login$', 'views.weibo_login', name='weibo_login'),
    url(r'^weibo_auth_end$', 'views.weibo_auth_end', name='weibo_auth_end'),
    url(r'^weibo_logout$', 'views.weibo_logout', name='weibo_logout'),
    url(r'^tweibo_login$', 'views.tweibo_login', name='tweibo_login'),
    url(r'^tweibo_auth_end$', 'views.tweibo_auth_end', name='tweibo_auth_end'),
    url(r'^tweibo_logout$', 'views.tweibo_logout', name='tweibo_logout'),
    url(r'^qq_auth_end$', 'views.qq_auth_end', name='qq_auth_end'),
    url(r'^qq_logout$', 'views.qq_logout', name='qq_logout'),
    url(r'^qq_call_back$', 'views.qq_call_back', name='qq_call_back'),
)

bookbar/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('bookbar',
    url(r'^(\d+)/$', 'views.bookbar', name='bookbar'),
    url(r'^addbook$', 'views.addbook', name='addbook'),
    url(r'^adddownloadurl/(\d+)/$', 'views.adddownloadurl', name='adddownloadurl'),
#    url(r'^booklist/(\d+)/(\d+)/$', 'views.booklist', name='booklist'),
    url(r'^bookalldetail/(\d+)/(\d+)/(\d+)/(\d+)/$', 'views.bookalldetail', name='bookalldetail'),
    url(r'^downloadurllist/(\d+)/(\d+)/$', 'views.downloadurllist', name='downloadlist'),
    url(r'^booksmalllist/(\d+)/$', 'views.booksmalllist', name='booksmalllist'),
    url(r'^downloadbook/(\d+)/$', 'views.downloadbook', name='downloadbook'),
    url(r'^downloadurldetail/(\d+)/(\d+)/$', 'views.downloadurldetail', name='downloadurldetail'),
    url(r'^addarticle$', 'views.addarticle', name='addarticle'),
    url(r'^addarticleend/(\d+)/(\d+)/(\d+)/$', 'views.addarticleend', name='addarticleend'),
    url(r'^articledetail/(\d+)/(\d+)/(\d+)/$', 'views.articledetail', name='articledetail'),
    url(r'^downloadurlalllist/(\d+)/(\d+)/$', 'views.downloadurlalllist', name='downloadurlalllist'),
    url(r'^articlelist/(\d+)/(\d+)/$', 'views.articlelist', name='articlelist'),
    url(r'^addadvice/(\d+)/$', 'views.addadvice', name='addadvice'),
    url(r'^sharebook/$', 'views.sharebook', name='sharebook'),
    url(r'^edit_article/(\d+)/$', 'views.edit_article', name='edit_article'),

    # Examples:
    # url(r'^$', 'bookbook.views.home', name='home'),
    # url(r'^bookbook/', include('bookbook.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

bookbook/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'django.views.generic.simple.redirect_to', {'url':'/bookbar/0/'}),
    url(r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url':'/static/favicon.ico'}),

    url(r'^bookbar/', include('bookbar.urls')),
    url(r'^bookqa/', include('bookqa.urls')),
    url(r'^auth/', include('auth.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

bookbar/models.py
from django.db import models

# Create your models here.

class WebSite(models.Model):
    name    = models.CharField(max_length=32)
    comment = models.ManyToManyField('Comment')

    def __unicode__(self):
        return self.name

class User(models.Model):
    name      = models.CharField(max_length=32, primary_key=True)
    password  = models.CharField(max_length=32)
    join_time = models.DateTimeField(auto_now_add=True)

class Category(models.Model):
    name = models.CharField(max_length=20)

    def __unicode__(self):
        return self.name

class ArticleCategory(models.Model):
    name = models.CharField(max_length=20)

    def __unicode__(self):
        return self.name

class Comment(models.Model):
    content     = models.CharField(max_length=4096)
    create_time = models.DateTimeField(auto_now_add=True)
    user_name   = models.CharField(max_length=32) # user.name or anonymous user's ip
    user        = models.ForeignKey('User')

    def __unicode__(self):
        return self.content

class Book(models.Model):
    title           = models.CharField(max_length=32)
    category        = models.ForeignKey('Category')
    author_name     = models.CharField(max_length=20)

    tag             = models.CharField(max_length=64, blank=True)
    translator_name = models.CharField(max_length=20, blank=True)
    publisher       = models.CharField(max_length=32, blank=True)
    publisher_time  = models.DateField(blank=True, null=True)
    pic_url         = models.URLField(blank=True)
    isbn            = models.CharField(max_length=64, blank=True)
    comment      = models.ManyToManyField('Comment')
    up_num       = models.IntegerField()
    down_num     = models.IntegerField()

    def __unicode__(self):
        return self.title

class ExtensionName(models.Model):
    name = models.CharField(max_length=16)

    def __unicode__(self):
        return self.name

# word
# high picture
# middle
# low
class ClearType(models.Model):
    type = models.CharField(max_length=16)

    def __unicode__(self):
        return self.type

class BookDownloadURL(models.Model):
    filename     = models.CharField(max_length=32)
    extension_name = models.ForeignKey('ExtensionName')
    book         = models.ForeignKey('Book')
    url          = models.URLField()
    create_time  = models.DateTimeField(auto_now_add=True)
    download_num = models.IntegerField()
    user_name    = models.CharField(max_length=20)  # same to comment.user_name
    user         = models.ForeignKey('User')
    comment      = models.ManyToManyField('Comment')
    up_num       = models.IntegerField()
    down_num     = models.IntegerField()
    cleartype    = models.ForeignKey('ClearType')

    def __unicode__(self):
        return self.filename + self.extension_name 

class Article(models.Model):
    title       = models.CharField(max_length=50)
    content     = models.TextField()
    user_name   = models.CharField(max_length=20)   # same to comment.user_name
    user        = models.ForeignKey('User')
    bookname    = models.CharField(max_length=1024, blank=True) # book name it related, split by ; or ,
    book        = models.ManyToManyField('Book')
    create_time = models.DateTimeField(auto_now_add=True)
    up_num      = models.IntegerField()
    down_num    = models.IntegerField()
    comment     = models.ManyToManyField('Comment')
    show_num    = models.IntegerField()
    category    = models.ForeignKey('ArticleCategory')

    def __unicode__(self):
        return self.title

bookbar/views.py
# Create your views here.

from django.http import HttpResponse
from django.http import HttpResponseRedirect
# from django.http import Http404
from django.shortcuts import render_to_response
from django.template import RequestContext

from bookbar.forms import BookForm
from bookbar.forms import BookDownloadURLForm
from bookbar.forms import CommentForm
from bookbar.forms import ArticleForm

from bookbar.models import User
from bookbar.models import Book
from bookbar.models import BookDownloadURL
from bookbar.models import ExtensionName
from bookbar.models import ClearType
from bookbar.models import Comment
from bookbar.models import Article
from bookbar.models import WebSite

def bookbar(request, category):
    max_download_urls = BookDownloadURL.objects.order_by('-download_num')[0:10]
    max_show_articles = Article.objects.order_by('-show_num')[0:10]
    latest_download_urls = BookDownloadURL.objects.order_by('-create_time')[0:10]
    latest_show_articles = Article.objects.order_by('-create_time')[0:10]

    context = {
        'max_download_urls': max_download_urls,
        'max_show_articles': max_show_articles,
        'latest_download_urls': latest_download_urls,
        'latest_show_articles': latest_show_articles,
    }
 
    return render_to_response('bookbar_home.html', context, 
            context_instance = RequestContext(request))

def edit_article(request, article_id):
    articles = Article.objects.filter(id=article_id)
    if articles.count() == 0:
        return HttpResponse("error")

    article = articles[0]    
    
    if request.method == 'GET':
        article_form = ArticleForm(initial = {
            'bookname': article.bookname,
            'title'   : article.title,
            'content' : article.content,
            'category': article.category,
        })

        context = {'articleform':article_form}

        return render_to_response('addarticle2.html', context, 
            context_instance = RequestContext(request))

    # POST
    article_form = ArticleForm(request.POST)
    context     = {'articleform':article_form, }

    if not article_form.is_valid():
        return render_to_response('addarticle2.html', 
            context, 
            context_instance = RequestContext(request))


    article.title    = article_form.cleaned_data['title']
    article.content  = article_form.cleaned_data['content']
    article.bookname = article_form.cleaned_data['bookname']
    article.category = article_form.cleaned_data['category']

    article.save()

    url = "/bookbar/articledetail/" + article_id + "/0/0/" 
    return HttpResponseRedirect(url)

def addarticle(request):
    # GET
    if request.method == 'GET':
        if 'bookname' in request.GET:
            articleform = ArticleForm(initial={'bookname': request.GET['bookname']})
        else:
            articleform = ArticleForm()

        context = {'articleform':articleform}

        return render_to_response('addarticle2.html', context, 
            context_instance = RequestContext(request))

    # POST
    # raise BaseException
    articleform = ArticleForm(request.POST)
    context     = {'articleform':articleform, }

    if not articleform.is_valid():
        return render_to_response('addarticle2.html', 
            context, 
            context_instance = RequestContext(request))

    # TODO: only support anonymous now
    anonymous = User.objects.filter(name = "anonymous")
    if anonymous.count() == 0:
        user = User(name="anonymous", password="password")
        user.save()
    else:
        user = anonymous[0]
 
    article = Article()
    article.title = articleform.cleaned_data['title']
    article.content = articleform.cleaned_data['content']
    article.user_name = request.META['REMOTE_ADDR'] # TODO:
    article.user = user
    article.up_num = 0
    article.down_num = 0
    article.show_num = 0
    article.bookname = articleform.cleaned_data['bookname']
    article.category = articleform.cleaned_data['category']

    article.save()

    url = '/bookbar/addarticleend/' + str(article.id) + "/0/0/"
    return HttpResponseRedirect(url)

def addarticleend_get(request, article_id, related_page_index, find_page_index):
    if not Article.objects.filter(id=article_id).count > 0:
        return HttpResponse("error")

    article = Article.objects.filter(id=article_id)[0]

    books = []
    booknames = article.bookname.split('#')

    for bookname in booknames:
       all_books = Book.objects.filter(title__icontains=bookname).all()

       for book in all_books:
           if book not in article.book.all():
               books.append(book)
    related_books_info = get_array_page_i(books, "related_books", int(related_page_index), 2)

    if 'find_book_name' in request.GET:
        all_books = []
        books = []
        all_books = Book.objects.filter(title__icontains=request.GET['find_book_name'])

        for book in all_books:
           if book not in article.book.all():
               books.append(book)
   
        finded_books_info = get_array_page_i(books, "finded_books", int(find_page_index), 2)
        finded_books_info.update({'find_book_name': request.GET['find_book_name']})
    else:
        finded_books_info = get_array_page_i([], "", 0, 1)
        finded_books_info.update({'find_book_name': ""})
    
    context = {
        'related_books_info': related_books_info,
        'finded_books_info': finded_books_info,
        'maped_books':  article.book.all(),
        'bookform': BookForm(),
        'article_id':article_id,
    }

    return render_to_response('addarticleend.html',
        context,
        context_instance=RequestContext(request))


def addarticleend_post(request, article_id, related_page_index, find_page_index):
    article = Article.objects.filter(id=article_id)[0]
    getstr=""

    if request.POST['submit_type'] == 'map_related_book':
        book_id = int(request.POST['submit_value'].split('_')[0])
        book = Book.objects.filter(id=book_id)[0]
        article.book.add(book)
        article.save()
    elif request.POST['submit_type'] == 'find_book':
         getstr = "?find_book_name=" + request.POST['find_book_name']
    elif request.POST['submit_type'] == 'map_finded_book':
        book_id = int(request.POST['submit_value'].split('_')[0])
        book = Book.objects.filter(id=book_id)[0]
        article.book.add(book)
        article.save()
        getstr = "?find_book_name=" + request.POST['find_book_name']
    elif request.POST['submit_type'] == 'add_new_and_map':
        bookform = BookForm(request.POST)

        if not bookform.is_valid():
            return render_to_response('addarticleend.html', 
            {'bookform':bookform},
            context_instance = RequestContext(request))

        # TODO: only support anonymous now
        anonymous = User.objects.filter(name = "anonymous")
        if anonymous.count() == 0:
            user = User(name="anonymous", password="password")
            user.save()
        else:
            user = anonymous[0]
     
        book = Book()
        book.title = bookform.cleaned_data['title']
        book.publisher = bookform.cleaned_data['publisher']
        book.publisher_time = bookform.cleaned_data['publisher_time']
        book.category = bookform.cleaned_data['category']
        book.tag = bookform.cleaned_data['tag']
        book.author_name = bookform.cleaned_data['author_name']
        book.translator_name = bookform.cleaned_data['translator_name']
        book.pic_url = bookform.cleaned_data['pic_url']
        book.isbn = bookform.cleaned_data['isbn']
        book.up_num = 0
        book.down_num = 0
        
        book.save()

        article.book.add(book)
        article.save()

    return HttpResponseRedirect('/bookbar/addarticleend/' 
        + article_id + "/" + related_page_index + "/" + find_page_index + getstr)

def addarticleend(request, article_id, related_page_index, find_page_index):
    if request.method == 'GET':
        return addarticleend_get(request, article_id, related_page_index, find_page_index)
    else:
        return addarticleend_post(request, article_id, related_page_index, find_page_index)

def articledetail(request, article_id, book_page_index, comment_page_index):
    if not Article.objects.filter(id=article_id).count > 0:
        return HttpResponse("error")

    article = Article.objects.filter(id=article_id)[0]
    article.show_num += 1
    article.save()

    one_page_num = 10

    book_dict = get_query_set_page_i(article.book.all(), "books", int(book_page_index), one_page_num)
    comment_dict = get_query_set_page_i(article.comment.all(), "comments", int(comment_page_index), one_page_num)

    context = {'article': article, 'book_dict':book_dict, 'comment_dict':comment_dict}
    
    if request.method == 'GET':
        context.update({'commentform':CommentForm()})
        return render_to_response('articledetail.html', 
            context,
            context_instance = RequestContext(request))
    else:
        commentform = CommentForm(request.POST) 
        if commentform.is_valid():
            # TODO: only support anonymous now
            anonymous = User.objects.filter(name = "anonymous")
            if anonymous.count() == 0:
                user = User(name="anonymous", password="password")
                user.save()
            else:
                user = anonymous[0]

            comment=Comment()
            comment.content = commentform.cleaned_data['content']
            comment.user_name = request.META['REMOTE_ADDR'] # TODO:
            comment.user = user
            comment.save()

            article.comment.add(comment)
            article.save()
 
            url = "/bookbar/articledetail/" + article_id + "/" + book_page_index + "/" + comment_page_index + "/"
            return HttpResponseRedirect(url)
        else:
            context.update({'commentform':commentform})
            return render_to_response('articledetail.html', 
                context,

bookbar/templates/addbook.html
{% extends "base.html" %}

{% block head %}
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8" />
    <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}/calendar/tcal.css" />
    <script type="text/javascript" src="{{STATIC_URL}}/calendar/tcal.js"></script> 
{% endblock %}

{% block content %}

<form action="" method="post">
{% csrf_token %}
<table>
    <tr>
        <td><span style="color:red">*</span>title:</td>   
        <td>{{bookform.title}}</td>
        <td>{{bookform.title.errors}}</td>
    </tr>  
    
    <tr>
        <td><span style="color:red">*</span>category:</td>
        <td>{{bookform.category}}</td>
        <td>{{bookform.category.errors}}</td>
    </tr>       
    
    <tr>
        <td>tag:</td>
        <td>{{bookform.tag}}</td>
        <td>{{bookform.tag.errors}}</td>
    </tr>
    
    <tr>
        <td><span style="color:red">*</span>author name:</td>
        <td>{{bookform.author_name}}</td>
        <td>{{bookform.author_name.errors}}</td>
    </tr>
    
    <tr>
        <td>translator name:</td>
        <td>{{bookform.translator_name}}</td>
        <td>{{bookform.translator_name.errors}}</td>
    </tr>
    
    <tr>
        <td>publisher:</td>
        <td>{{bookform.publisher}}</td>
        <td>{{bookform.publisher.errors}}</td>
    </tr>
    
    <tr>
        <td>publisher date:</td>
        <td>
            <input type="text" name="publisher_time" id="id_publisher_time" class="tcal"/>
        </td>
        <td>{{bookform.publisher_time.errors}}</td>
    </tr>
    
    <tr>
        <td>picture URL:</td>
        <td>{{bookform.pic_url}}</td>
        <td>{{bookform.pic_url.errors}}</td>
    </tr>
    
    <tr>
        <td>ISBN:</td>
        <td>{{bookform.isbn}}</td>
        <td>{{bookform.isbn.erros}}</td>
    </tr>
    
    <tr>
        <td></td>
        <td><input type="submit" value="submit"></td>
        <td></td>
    </tr>
</table>
</form>
{% endblock %}

bookbar/templates/addbookend.html
{% extends "base.html" %}

{% block content %}


add book ok! <br/><br/>

thanks<br/><br/>


You Can:<br/><br/>


1. <a href="/bookbar/bookalldetail/{{book.id}}/0/0/0/">view this book</a> <br/> <br/>

2. <a href="/bookbar/adddownloadurl/{{book.id}}/">add download url</a> <br/> <br/>

3. add article <br/> <br/>

4. <a href="/bookbar/addbook/">continue add a book</a> <br/><br/>

5. <a href="/bookbar/sharebook/">continue share a book</a> <br/><br/>

6. <a href="/">go home</a> <br/> <br/>

{% endblock %}

bookbar/templates/adddownloadurl.html
 
{% extends "base.html" %}
{% block content %}


{% include 'bookdetail.html' %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{downloadurlform.as_table }}
    </table>
    <input type="submit" value="Submit" />
</form>

{% endblock %}

bookbar/templates/advice.html
{% extends "base.html" %}

{% block head %}

<script src="http://tjs.sjs.sinajs.cn/open/api/js/wb.js?appkey=3544153356" type="text/javascript" charset="utf-8"></script>

{% endblock %}

{% block content %}

<script>
var ping_lun_box = "" +
    "<wb:comments url=\""   +
    "http://bookbook.tk"   + 
    window.location.pathname +
    "\" border=\"y\" fontsize=\"12\" width=\"auto\" appkey=\"3544153356\" ></wb:comments>"
document.write(ping_lun_box);
</script>

{% endblock %}

bookbar/templates/bookbar_home.html
{% extends "base.html" %}

{% block head %}

<title>book</title>

<meta name="description" content="&#x81F4;&#x529B;&#x4E8E;&#x6253;&#x9020;&#x4E00;&#x4E2A;&#x8BFB;&#x4E66; &#x5B66;&#x4E60; &#x4EA4;&#x6D41;&#x7684;&#x5E73;&#x53F0;"/>
<meta name="keywords" content="&#x7535;&#x5B50;&#x4E66;,&#x4E0B;&#x8F7D;,&#x7ECF;&#x5178;&#xFF0C;&#x4E66;&#x7C4D;&#xFF0C;,pdf, linux,bookbook"/>

{% endblock %}


{% block content %}

<div style="width:100%;margin:20px auto;">

<ul>
    <table border="0">
    <tr>
        <td colspan="6">
            <h4> &#x6700;&#x591A;&#x4E0B;&#x8F7D; <!-- zui duo xia zai --> </h4>
        </td>
    </tr>

    {% for url in max_download_urls %}
    <tr>
         <td><li></li></td>
         <td class="td_category"> [{{url.book.category}}] </td>
         <td class="td_title">
             <a href="/bookbar/downloadurldetail/{{url.id}}/0">{{url.filename|slice:"30"}}{{url.extension_name}}</a> 
         </td>
         <td class="td_user">{{url.user_name|slice:"15"}}</td>
         <td class="td_time">{{url.create_time|date:"m-d H:i"}}</td>
         <td class="td_num" >{{url.download_num}} </td>
         <td><a href="/bookbar/downloadbook/{{url.id}}/">&#x4E0B;&#x8F7D;</a></td>
    </tr>
    {% endfor %}

    <tr>
        <td colspan="4"> 
        </td>
        <td>
            <a href="/bookbar/downloadurlalllist/0/0/">view more </a> 
        </td>
        <td></td>
    </tr>
    </table>
</ul>


<ul>
    <table>
    <tr>
        <td colspan="6"><h4> &#x6700;&#x591A;&#x9605;&#x8BFB; </h4></td> <!-- zui duo xian shi -->
    </tr>

    {% for article in max_show_articles %}
    <tr>
         <td><li></li></td>
         <td class="td_category"> [{{article.category}}]</td>
         <td class="td_title"> 
             <span title="{{article.content|striptags}}"> 
             <a href="/bookbar/articledetail/{{article.id}}/0/0/">{{article.title|slice:"30"}}</a>
             </span>
         </td>
         <td class="td_user">{{article.user_name|slice:"15"}}</td>
         <td class="td_time">{{article.create_time|date:"m-d i:s"}}</td>
         <td class="td_num" >{{article.show_num}}</td>
    </tr>
    {% endfor %}

    <tr>
        <td colspan="4"> 
        </td>
        <td>
            <a href="/bookbar/booksmalllist/0/">view more </a> 
        </td>
        <td></td>
    </tr>
    </table>
</ul>

<ul>
    <table>
    <tr>
        <td colspan="6"> <h4>&#x6700;&#x65B0;&#x4E0A;&#x4F20;</h4> </td>
    </tr>

    {% for url in latest_download_urls %}
    <tr>
         <td><li></li></td>
         <td class="td_category"> [{{url.book.category}}] </td>
         <td class="td_title">
             <a href="/bookbar/downloadurldetail/{{url.id}}/0">{{url.filename|slice:"30"}} {{url.extension_name}}</a>
         </td>
         <td class="td_user">{{url.user_name|slice:"15"}}</td>
         <td class="td_time">{{url.create_time|date:"m-d H:i"}}</td>
         <td><a href="/bookbar/downloadbook/{{url.id}}/">&#x4E0B;&#x8F7D;</a></td>
    </tr>
    {% endfor %}

    <tr>
        <td colspan="4"> </td>
        <td>
            <a href="/bookbar/downloadurlalllist/0/0/">view more </a> 
        </td>
    </tr>
    </table>
</ul>

<ul>
    <table>
    <tr>
        <td colspan="6"> <h4>&#x6700;&#x65B0;&#x53D1;&#x5E03;</h4> </td>
    </tr>

    {% for article in latest_show_articles %}
    <tr>
         <td><li></li></td>
         <td class="td_category"> [{{article.category}}]</td>
         <td class="td_title">
             <span title="{{article.content|striptags}}"> 
             <a href="/bookbar/articledetail/{{article.id}}/0/0/">{{article.title|slice:"30"}}</a>
             </span>
         </td>
         <td class="td_user">{{article.user_name|slice:"15"}}</td>
         <td class="td_time">{{article.create_time|date:"m-d H:i"}}</td>
    </tr>
    {% endfor %}

    <tr>
        <td colspan="4"> </td>
        <td>
            <a href="/bookbar/booksmalllist/0/">view more </a> 
        </td>
    </tr>

    </table>
</ul>

</div>
{% endblock %}

bookbar/templates/sharebook.html
{% extends "base.html" %}

{% block head %}
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8" />
    <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}/calendar/tcal.css" />
    <script type="text/javascript" src="{{STATIC_URL}}/calendar/tcal.js"></script> 
{% endblock %}


{% block content %}

<form action="" method="post">
{% csrf_token %}
<table>
    <tr>
        <td><span style="color:red">*</span>title:</td>   
        <td>{{bookform.title}}</td>
        <td>{{bookform.title.errors}}</td>
    </tr>  
    
    <tr>
        <td><span style="color:red">*</span>category:</td>
        <td>{{bookform.category}}</td>
        <td>{{bookform.category.errors}}</td>
    </tr>       
    
    <tr>
        <td>tag:</td>
        <td>{{bookform.tag}}</td>
        <td>{{bookform.tag.errors}}</td>
    </tr>
    
    <tr>
        <td><span style="color:red">*</span>author name:</td>
        <td>{{bookform.author_name}}</td>
        <td>{{bookform.author_name.errors}}</td>
    </tr>
    
    <tr>
        <td>translator name:</td>
        <td>{{bookform.translator_name}}</td>
        <td>{{bookform.translator_name.errors}}</td>
    </tr>
    
    <tr>
        <td>publisher:</td>
        <td>{{bookform.publisher}}</td>
        <td>{{bookform.publisher.errors}}</td>
    </tr>
    
    <tr>
        <td>publisher date:</td>
        <td>
            <input type="text" name="publisher_time" id="id_publisher_time" class="tcal"/>
        </td>
        <td>{{bookform.publisher_time.errors}}</td>
    </tr>
    
    <tr>
        <td>picture URL:</td>
        <td>{{bookform.pic_url}}</td>
        <td>{{bookform.pic_url.errors}}</td>
    </tr>
    
    <tr>
        <td>ISBN:</td>
        <td>{{bookform.isbn}}</td>
        <td>{{bookform.isbn.errors}}</td>
    </tr>
     
    {{downloadurlform.as_table }}

    <tr>
        <td></td>
        <td><input type="submit" value="submit"></td>
        <td></td>
    </tr>
</table>
</form>

{% endblock %}