auth/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('auth',
    url(r'^weibo_login$', 'views.weibo_login', name='weibo_login'),
    url(r'^weibo_auth_end$', 'views.weibo_auth_end', name='weibo_auth_end'),
    url(r'^weibo_logout$', 'views.weibo_logout', name='weibo_logout'),
    url(r'^tweibo_login$', 'views.tweibo_login', name='tweibo_login'),
    url(r'^tweibo_auth_end$', 'views.tweibo_auth_end', name='tweibo_auth_end'),
    url(r'^tweibo_logout$', 'views.tweibo_logout', name='tweibo_logout'),
    url(r'^qq_auth_end$', 'views.qq_auth_end', name='qq_auth_end'),
    url(r'^qq_logout$', 'views.qq_logout', name='qq_logout'),
    url(r'^qq_call_back$', 'views.qq_call_back', name='qq_call_back'),
)

bookbook/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'django.views.generic.simple.redirect_to', {'url':'/bookbar/0/'}),
    url(r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url':'/static/favicon.ico'}),

    url(r'^bookbar/', include('bookbar.urls')),
    url(r'^bookqa/', include('bookqa.urls')),
    url(r'^auth/', include('auth.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

bookqa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('bookqa',
    url(r'^$', 'views.qa_list', {'category_id':"0",'page_num':"0"}),
    url(r'^qa_list/(\d+)/(\d+)/$', 'views.qa_list', name='qa_list'),
    url(r'^topic_detail/(\d+)/(\d+)/$', 'views.topic_detail', name='topic_detail'),
    url(r'^comment_detail/(\d+)/(\d+)/$', 'views.comment_detail', name='comment_detail'),
    url(r'^qa_add_question/$', 'views.qa_add_question', name='qa_add_question'),
    url(r'^tag_list/(\d+)/$', 'views.tag_list', name='tag_list'),
    #url(r'^sharebook/$', 'views.sharebook', name='sharebook'),

    # Examples:

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

bookqa/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class BookName(models.Model):
    name = models.CharField(max_length=40)

    def __unicode__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=40)

    def __unicode__(self):
        return self.name

# in book category, it's a book name
# in open source category, it's a project name
class QaTag(models.Model): 
    name = models.CharField(max_length=40)

    def __unicode__(self):
        return self.name

# a comment can belong to a Topic or a comment
class Comment(models.Model):
    content        = models.TextField()

    user           = models.ForeignKey(User, blank=True, null=True)
    user_name      = models.CharField(max_length=20)   # same to User.username or ip of anonymous user
    topic_parent   = models.ForeignKey('Topic', blank=True, null=True)
    comment_parent = models.ForeignKey('self', blank=True, null=True)

    up_num         = models.IntegerField()
    down_num       = models.IntegerField()
    show_num       = models.IntegerField()
 
    is_best        = models.BooleanField()

    create_time    = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-create_time']

class Topic(models.Model):
    title       = models.CharField(max_length=512)
    category    = models.ForeignKey('Category')
    tag         = models.ForeignKey('QaTag')
    content     = models.TextField()

    user        = models.ForeignKey(User, blank=True, null=True)
    user_name   = models.CharField(max_length=20)   # same to User.username or ip of anonymous user
    create_time = models.DateTimeField(auto_now_add=True)

    up_num      = models.IntegerField()
    down_num    = models.IntegerField()
    show_num    = models.IntegerField()
   
    is_solve    = models.BooleanField()

    class Meta:
        ordering = ['-create_time']

bookqa/forms.py
from django import forms

from bookqa.models import Topic
from bookqa.models import Comment

class TopicForm(forms.ModelForm):
    tag_name = forms.CharField(max_length=40)
    class Meta:
        model  = Topic
        fields = ('title', 'content', 'category')

class CommentForm(forms.ModelForm):
    class Meta:
        model  = Comment
        fields = ('content', )

bookqa/views.py
# Create your views here.

from django.http import HttpResponse
from django.http import HttpResponseRedirect
# from django.http import Http404
from django.shortcuts import render_to_response
from django.template import RequestContext

from bookqa.models import Topic
from bookqa.models import QaTag
from bookqa.models import Category
from bookqa.models import Comment

from bookqa.forms import TopicForm
from bookqa.forms import CommentForm

def qa_list(request, category_id, page_num):
    if request.method == "POST":
        return HttpResponse("error: do not support post  ")

    if category_id == "0":
        topics = Topic.objects.all()
    else:
        category = Category.objects.get(id=category_id)
        topics   = category.topic_set.all()

    one_page_count = 50

    context = {
        "categorys": Category.objects.all(),
        "topic_dict":
        get_query_set_page_i(topics, "topics", int(page_num), one_page_count),
        "category_id": int(category_id)
    }

    return render_to_response('qa_list.html', context, 
            context_instance = RequestContext(request))

def qa_add_question(request):
    if request.method == 'GET':
        form = TopicForm()
        context = { 'form': form, }
        return render_to_response('qa_add_question.html', context, 
            context_instance = RequestContext(request))
        
    # POST
    form = TopicForm(request.POST)

    if not form.is_valid():
        context = { 'form': form, }
        return render_to_response('qa_add_question.html', context, 
            context_instance = RequestContext(request))

    tag_name = form.cleaned_data['tag_name']
    try:
        tag = QaTag.objects.get(name=tag_name)
    except QaTag.DoesNotExist:
        tag = QaTag(name=tag_name)
        tag.save()

    topic = Topic()
    topic.title = form.cleaned_data['title']
    topic.category = form.cleaned_data['category']
    topic.tag = tag;
    topic.content = form.cleaned_data['content']

    if request.user.is_authenticated():
        topic.user      = request.user
        topic.user_name = request.user.last_name
    else:
        topic.user_name = request.META['REMOTE_ADDR'] # TODO:

    topic.up_num = 0
    topic.down_num = 0 
    topic.show_num = 0

    topic.is_solve = False

    topic.save()

    return HttpResponseRedirect('/bookqa/qa_list/0/0/')

def comment_detail(request, comment_id, child_comment_page_num):
    try:
        comment = Comment.objects.get(id=comment_id)
    except Comment.DoesNotExist:
        return HttpResponse("error: comment does not exist ")

    if request.method == 'GET':
        child_comments = comment.comment_set.all()
         
        one_page_count = 50
        context = {
            'comment':comment,
            'child_comment_dict':
                get_query_set_page_i(child_comments, "child_comments", int(child_comment_page_num), one_page_count),
            'form': CommentForm(),
        }

        return render_to_response('comment_detail.html', context, 
            context_instance = RequestContext(request))

    form = CommentForm(request.POST)

    if not form.is_valid():
        context = {
            'comment':comment,
            'form': form,
        }

        return render_to_response('comment_detail.html', context, 
            context_instance = RequestContext(request))

    child_comment = Comment()
    child_comment.content = form.cleaned_data['content']

    if request.user.is_authenticated():
        child_comment.user      = request.user
        child_comment.user_name = request.user.last_name
    else:
        child_comment.user_name = request.META['REMOTE_ADDR'] # TODO:

    child_comment.comment_parent  = comment

    child_comment.up_num   = 0
    child_comment.down_num = 0
    child_comment.show_num = 0
    child_comment.is_best  = False
   
    child_comment.save()

    url = "/bookqa/comment_detail/" + comment_id + "/0/"

    return HttpResponseRedirect(url)

def topic_detail(request, topic_id, comment_page_num):
    try:
        topic = Topic.objects.get(id=topic_id)
    except Topic.DoesNotExist:
        return HttpResponse("error: topic does not exist ")

    if request.method == 'GET':
        comments = topic.comment_set.all()
        try:
            best_comment = comments.get(is_best=True)
        except Comment.DoesNotExist:
            best_comment = 0

        one_page_count = 50
        context = {
           'topic':topic,
           'best_comment':best_comment,
           'comment_dict': get_query_set_page_i(comments, "comments", int(comment_page_num), one_page_count),
           'form'  : CommentForm(),
        }

        return render_to_response('topic_detail.html', context, 
            context_instance = RequestContext(request))

    # POST
    form = CommentForm(request.POST)
    if not form.is_valid():
        context = {
            'topic':topic,
            'form': form,
        }
        return render_to_response('topic_detail.html', context, 
            context_instance = RequestContext(request))

    comment = Comment()
    comment.content = form.cleaned_data['content']

    if request.user.is_authenticated():
        comment.user      = request.user
        comment.user_name = request.user.last_name
    else:
        comment.user_name = request.META['REMOTE_ADDR'] # TODO:

    comment.topic_parent  = topic

    comment.up_num   = 0
    comment.down_num = 0
    comment.show_num = 0
    comment.is_best  = False
   
    comment.save()

    url = "/bookqa/topic_detail/" + topic_id + "/0/"
    return HttpResponseRedirect(url)


def get_query_set_page_i(set, set_name, i, one_page_count):
    total = set.count()
 
    total_page = total / one_page_count

    if total % one_page_count != 0:
        total_page += 1

    if total_page == 0:
        return {
            'current_page_show':0,
            'current_page':0, 
            'prev_page':0, 
            'next_page':0, 
            'total_page':0, 
            set_name:set, 
    } 

    current_page = i
    if current_page < 0:
        current_page = 0
    if current_page >= total_page:
        current_page = total_page -1

    prev_page = current_page - 1
    if prev_page < 0:
        prev_page = 0
  
    next_page = current_page + 1
    if next_page >= total_page:
        next_page = total_page - 1
    
    set1 = set[current_page * one_page_count:]


    if(set1.count() > one_page_count):
        set2 = set1[:one_page_count]
    else:
        set2 = set1

    current_page_show = current_page + 1

    return {
        'current_page_show': current_page_show, 
        'current_page': current_page, 
        'prev_page': prev_page,
        'next_page': next_page, 
        'total_page':total_page, 
        set_name:set2
    }
     
def tag_list(request, page_num):
    tags = QaTag.objects.all()
    one_page_count = 2

    context = {
        'tag_dict': get_query_set_page_i(tags, "tags", int(page_num), one_page_count),
    }

    return render_to_response('tag_list.html', context, 
        context_instance = RequestContext(request))

bookqa/templates/comment_detail.html
{% extends "qa_base.html" %}

{% block head %}

<meta charset="utf-8" />

<link rel="stylesheet" href="{{STATIC_URL}}/kindeditor-4.1.10/themes/default/default.css" />
<script charset="utf-8" src="{{STATIC_URL}}/kindeditor-4.1.10/kindeditor-min.js"></script>
<script charset="utf-8" src="{{STATIC_URL}}/kindeditor-4.1.10/lang/zh_CN.js"></script>

<script>
    var editor;

    KindEditor.ready(function(K) {
        editor = K.create('textarea[name="content"]', {
            resizeType : 1,
            allowPreviewEmoticons : false,
            allowImageUpload : false,
            items : [
                'fontname', 'fontsize', '|', 'forecolor', 'hilitecolor', 'bold', 'italic', 'underline',
                'removeformat', '|', 'justifyleft', 'justifycenter', 'justifyright', 'insertorderedlist',
                'insertunorderedlist', '|', 'emoticons', 'image', 'link']
        });
    });

</script>

<style type="text/css">

.qa-voting {
    color: #555;
    font-weight:bold;
    background: none repeat scroll 0% 0% #F1FBFE;
    border: 1px solid #CDE2ED;
    border-radius: 2px;
    float: left;
    height: 48px;
    overflow: hidden;
    margin: 6px 16px 0px 0px;
    padding: 8px 0px;
    width: 60px;
    text-align:center;
}
.qa-a-count-none {
    text-align:center;
    color: #555;
    font-weight:bold;
    background: none repeat scroll 0% 0% #F9FFEC;
    border: 1px solid #DBE6CB;
    border-radius: 2px;
    text-align: center;
    width: 60px;
    height: 48px;
    overflow: hidden;
    float: left;
    margin: 6px 16px 0px 0px;
    padding: 8px 0px;
}
.qa-q-item-meta {
    color: #999;
    display: inline-block;
    vertical-align: middle;
    margin-top: 6px;
}


</style>

<script type="text/javascript" src="http://lib.sinaapp.com/js/jquery/1.9.1/jquery-1.9.1.min.js"></script>
<script type="text/javascript">
function toggle_comment(obj) {
    obj_id = parseInt(obj.id)
    var content="comment_"  + obj_id.toString()
    var content_thumb="comment_thumb_" + obj_id.toString()

    if($('#' + content).is(":hidden")) {
        obj.innerHTML = "\u6536\u8D77"
    } else {
        obj.innerHTML = "\u5C55\u5F00"
    }

    //obj.value = ($('#' + content).is(":hidden") ? "\u6536\u8D77" : "\u5C55\u5F00");
    $('#' + content_thumb).slideToggle(0);
    $('#' +  content).slideToggle();
}

function toggle_child_comment(obj) {
    obj_id = parseInt(obj.id)
    var content="child_comment_"  + obj_id.toString()
    var content_thumb="child_comment_thumb_" + obj_id.toString()

    if($('#' + content).is(":hidden")) {
        obj.innerHTML = "\u6536\u8D77"
    } else {
        obj.innerHTML = "\u5C55\u5F00"
    }

    //obj.value = ($('#' + content).is(":hidden") ? "\u6536\u8D77" : "\u5C55\u5F00");
    $('#' + content_thumb).slideToggle(0);
    $('#' +  content).slideToggle();
}
</script>


{% endblock %}

{% block content %}

<table border="0" width="100%">
    <tr>
        <td style="width:50px;height:100%"> 
        <table border="0" style="height:100%">
            <tr><td> <div class="qa-a-count-none"> up </div> </td></tr>
            <tr><td style="height:100%;"></td></tr>
        </table>
        </td>
        <td> 
        {% autoescape off %}
        {{comment.content}} 
        {% endautoescape %}
        </td>
    </tr>

    <tr>
        <td></td> 
        <td> 
           <span class="qa-q-item-meta" style="float:right">
              &#x65F6;&#x95F4;: &nbsp;{{comment.create_time|date:"Y-m-d H:i"}} 
              &nbsp;&nbsp;&nbsp;&#x4F5C;&#x8005;: &nbsp;{{comment.user_name}}
           </span>
<!-- <span style="float:right;padding-right:150px">{{comment.user_name}}{{comment.create_time}}</span> -->
        </td> 
    </tr>

    <tr>
        <td></td>
        <td>
            <form action="" method="post">
                {% csrf_token %}
                {{form.content.errors}}
                {{form.content}}
                <br/>
                <input type="submit" value="&#x56DE;&#x590D;"></input>
            </form>
        </td>
    </tr>

    <tr><td colspan="2"><hr/></td></tr>

    {% for child_comment in child_comment_dict.child_comments.all %}
    <tr> 
        <td></td> 
        <td style="word-break:break-all">
        {% if child_comment.content|length < 2048 %}
            <div> {{child_comment.content|safe}} </div>
        {% else %}
        <div style="display:none;" id="child_comment_{{child_comment.id}}"> {{child_comment.content|safe}} </div>
        <span id="child_comment_thumb_{{child_comment.id}}"> 
            {{child_comment.content|striptags|slice:":1024"}} ... ...
        </span> 
        <a style="font-size:11px;" href="javascript:void()" onclick="toggle_child_comment(this)" id="{{child_comment.id}}_button">&#x5C55;&#x5F00;</a>
        {% endif %}
 
        </td>
    </tr>

    <tr> 
        <td></td> 
        <td>
           <span class="qa-q-item-meta" style="float:right">
              &#x65F6;&#x95F4;: &nbsp;{{child_comment.create_time|date:"Y-m-d H:i"}} 
              &nbsp;&nbsp;&nbsp;&#x4F5C;&#x8005;: &nbsp;{{child_comment.user_name}}
           </span>
        </td>
    </tr>
    
    <tr><td colspan="2"><br/></td></tr>
    {% endfor %}

    <tr>
        <td></td>
        <td>
            <span style="float:right;padding-right:150px">
            {{child_comment_dict.current_page_show}} / {{child_comment_dict.total_page}}
            <a href="/bookqa/comment_detail/{{comment.id}}/{{child_comment_dict.prev_page}}/">&#x4E0A;&#x4E00;&#x9875;</a>
            <a href="/bookqa/comment_detail/{{comment.id}}/{{child_comment_dict.next_page}}/">&#x4E0B;&#x4E00;&#x9875;</a>
            </span>
        </td>
    </tr>
</table>
 

{% endblock %}

bookqa/templates/qa_add_question.html
{% extends "qa_base.html" %}

{% block head %}

<meta charset="utf-8" />

<link rel="stylesheet" href="{{STATIC_URL}}/kindeditor-4.1.10/themes/default/default.css" />
<script charset="utf-8" src="{{STATIC_URL}}/kindeditor-4.1.10/kindeditor-min.js"></script>
<script charset="utf-8" src="{{STATIC_URL}}/kindeditor-4.1.10/lang/zh_CN.js"></script>

<script>
    var editor;

    KindEditor.ready(function(K) {
        editor = K.create('textarea[name="content"]', {
            resizeType : 1,
            allowPreviewEmoticons : false,
            allowImageUpload : false,
            items : [
                'fontname', 'fontsize', '|', 'forecolor', 'hilitecolor', 'bold', 'italic', 'underline',
                'removeformat', '|', 'justifyleft', 'justifycenter', 'justifyright', 'insertorderedlist',
                'insertunorderedlist', '|', 'emoticons', 'image', 'link']
        });
    });

    /* KindEditor.ready(function(K) {
        editor = K.create('textarea[name="content"]', {
            allowFileManager : true
        });
    }); */
</script>

<style type="text/css">

#id_title {
    width:80%;
    height:20px;
}

#id_tag_name {
    width:50%;
    height:20px;
}
#id_content {
    display: block;
    width:780px;
    height:300px;
    visibility:hidden;
}

input#id_title {
    width:500px;
}

</style>

{% endblock %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table border="0">
        <tr>
            <td> <h4>&#x7528;&#x4E00;&#x53E5;&#x7B80;&#x5355;&#x660E;&#x4E86;&#x7684;&#x6807;&#x9898;&#x6982;&#x62EC;&#x4E0B;&#x4F60;&#x7684;&#x95EE;&#x9898;:</h4> </td>
        </tr>
        <tr> <td>{{form.title.errors}}</td> </tr>
        <tr> <td>{{form.title}}</td> </tr>
    
        <tr> <td><h4>&#x5206;&#x7C7B;:</h4></td> </tr>
        <tr> <td>{{form.category.errors}}</td> </tr>
        <tr> <td>{{form.category}}</td> </tr>
        
        <tr> <td><h4>TAG:</h4> </td> </tr>
        <tr> <td>{{form.tag_name.errors}}</td> </tr> 
        <tr> <td>{{form.tag_name}}</td> </tr>
    
        <tr>
            <td> <h4>&#x8BF7;&#x8BE6;&#x7EC6;&#x63CF;&#x8FF0;&#x4F60;&#x7684;&#x95EE;&#x9898;:</h4> </td>
        </tr>
        <tr> <td>{{form.content.errors}}</td> </tr>
        <tr> <td>{{form.content}}</td> </tr>
     
        <tr>
            <td> <input type="submit" value="&#x63D0;&#x4EA4;&#x95EE;&#x9898;"></input> </td>
        </tr>
    </table>
</form>


{% endblock %}

bookqa/templates/qa_base.html
{% extends "basebase.html" %}

{% block top_centre %}
    {% include 'qa_header.html' %}
    {% block header %}  {% endblock %} 
{% endblock %}

{% block middle_centre %}
    {% block content %} {% endblock %} 
{% endblock %}

{% block bottom_centre %}
    {% block footer %}  {% endblock %} 
    {% include 'footer.html' %}
{% endblock %}

bookqa/templates/qa_detail.html
{% extends "qa_base.html" %}

{% block content %}


<script> 

var last_td_id=""

function quote(obj)
{
    var id = parseInt(obj.id);
    var content_id = String(id) + "_content";


	var a = document.getElementById(content_id)
	var b = document.getElementById("id_content")

    b.value = a.innerHTML
}

function cancel(obj)
{
    if(last_td_id != "") {
        document.getElementById(last_td_id).innerHTML=""; 
    }


}

function check(obj) 
{ 
    
    if(last_td_id != "") {
        document.getElementById(last_td_id).innerHTML=""; 
    }

    var id = parseInt(obj.id);
    var td_id = String(id) + "_td";
    var b = "" +
"<form action=\"\" method=\"post\">"+
"{% csrf_token %}"+
"<input type=\"hidden\" id=\"id_title\" name=\"title\" value=\"" + "{{topic.title}}" + "\">  </input>" +
"<input type=\"hidden\" id=\"id_book_name\" name=\"book_name\" value=\"x {{topic.book_name}} \"></input>" +
"{{form.content|addslashes }}" +
"{{form.content.errors|addslashes }}" +
"<br/>" +
"<input type=\"submit\" value=\"answer\"></input>" +
"<input type=\"button\" value=\"cancel\" onClick=\"cancel(this)\"></input>" +
"<input type=\"hidden\" name=\"topic_id\" value=\"" + String(id) + "\"></input>" +
"</form>" +
"";

    document.getElementById(td_id).innerHTML=b; 

    last_td_id=td_id;
} 

</script>

<style type="text/css">

.qa-voting {
    color: #555;
    font-weight:bold;
    background: none repeat scroll 0% 0% #F1FBFE;
    border: 1px solid #CDE2ED;
    border-radius: 2px;
    float: left;
    height: 48px;
    overflow: hidden;
    margin: 6px 16px 0px 0px;
    padding: 8px 0px;
    width: 60px;
    text-align:center;
}
</style>

<br/> <br/> <br/>

{% if topic.parent %}
<table border="0" style="width:100%">
    <tr>
        <td colspan="2"> 
            <h3>
            [{{topic.parent.book_name}}] <a href="/bookqa/qa_detail/{{topic.parent.id}}/">{{topic.parent.title}}</a> 
            </h3>
        </td>
    </tr>

    <tr>
        <td rowspan="3" style="width:70px;position:relative;"> <div class="qa-voting"> up </div> </td>
    </tr>

    <tr>
        <td> {{topic.parent.content}} </td>
    </tr>

    <tr>
        <td>{{topic.parent.user_name}} {{topic.parent.create_time}}</td>
    </tr>
</table>
{% endif %}

<br/> <br/> <br/>

<table border="0" style="width:100%">
    {% if not topic.parent %}
    <tr>
        <td colspan="2"> 
            <h3>
            [{{topic.book_name}}] <a href="/bookqa/qa_detail/{{topic.id}}/">{{topic.title}}</a>
            </h3>
        </td>
    </tr>
    {% endif %}

    <tr>
        <td rowspan="3" style="width:70px;position:relative;"> 
            <div class="qa-voting"> up </div> 
        </td>
    </tr>

    <tr>
        <td> {{topic.content}} </td>
    </tr>

    <tr>
        <td>{{topic.user_name}} {{topic.create_time}}</td>
    </tr>
</table>

<br/> <br/><hr/>

{% if topic.topic_set.count %}
<table border="0" style="width:100%">
    {% for topic_answer in topic.topic_set.all %}

    <tr>
        <td colspan="2"><br/><br/></td>
    </tr>

    <tr>
        <td rowspan="2" style="width:70px;position:relative;"> <div class="qa-voting"> up </div> </td>

        <td id="{{topic_answer.id}}_content"> {{topic_answer.content}} </td>
    </tr>

    <tr>
        <td>{{topic.user_name}} {{topic.create_time}}</td>
    </tr>

    <tr>
        <td></td>
        <td>
            <table border="0" width="80%">
                {% for answer in topic_answer.topic_set.all|slice:":2" %}
                <tr>
                    <td rowspan="3" style="width:50px"></td>
                    <td> {{answer.content}} </td>
                </tr>

                <tr>
                    <td>{{topic.user_name}}  {{topic.create_time}}</td>
                </tr>

                <tr>
                    <td><div style="border-bottom:1px dashed;width=100%"></div></td>
                </tr>
                {% endfor %}
 
                <tr>
                    <td style="width:50px"></td>
                    <td> 
                       {% if topic_answer.level <= 1 %}
                       <input type="button" id="{{topic_answer.id}}_buttion" name="answer" value="&#x56DE;&#x590D;" onClick="check(this)"></input>
                       {% else %}
                       <input type="button" id="{{topic_answer.id}}_buttion" name="answer" value="&#x5F15;&#x7528;" onClick="quote(this)"></input>
                       {% endif %}
                       <a href="/bookqa/qa_detail/{{topic_answer.id}}/">view more</a>
                    </td>
                </tr>

                <tr>
                    <td></td>
                    <td id="{{topic_answer.id}}_td"> </td>
                </tr>
            </table>
        </td>
    </tr>
    {% endfor%} 

    <tr>
        <td colspan="2"><br/><br/><hr/></td>
    </tr>
</table>
{% endif %}

<br/>
<br/>
<br/>
<br/>
<div id="reply_div_id">
{% if topic.level <= 1%}
    <form action="" method="post">
    {% csrf_token %}
        <input type="hidden" id="id_title" name="title" value="{{topic.title}}" ></input>
        <input type="hidden" id="id_book_name" name="book_name" value="{{topic.book_name}}" ></input>
        <input type="hidden" value="{{topic.id}}" name="topic_id"></input>
        {{form.content.errors}}
        {{form.content}}
        <br/>
        <input type="submit" value="&#x56DE;&#x590D;"></input>
</form>
{% endif %}
</div>

{% endblock %}

bookqa/templates/qa_search.html
{% extends "qa_base.html" %}

{% block content %}

<form action="" method="get">

category:
<select name="category">
    <option value="0"> --- </option> 
    {% for category in categorys %}
        <option value="{{category.id}}">{{category}}</option> 
    {% endfor %}
</select> 

<input type="text" name="tag"></input>

<input type="text" name="user"></input>

<input type="text" name="keyword"></input>

</form>

{% endblock %}